### ISSUE TITLE
Code about ObjectNav evaluation 

### ISSUE THREAD

**Issue by zenght** [srama2512/PONI#2]
Hi, you have done a great job, and could you please release the objectNav evaluation code. It will be very helpful. Thanks.

**Comment by srama2512** [comment]
@zenght  - I'm currently traveling for some time. So our plan is to release the ObjectNav eval code by mid-August. Thanks for your patience.

**Comment by zenght** [comment]
Hello, can you please release the relevant ObjectNav codes? I'm looking forward to it.

**Comment by Routine113** [comment]
> Hi, you have done a great job, and could you please release the objectNav evaluation code. It will be very helpful. Thanks.

Excuse me！ I'd like to ask about the installation environment. Can you give me some advice?Thank you very much！！ My email is 1908795735@qq.com

**Comment by SJingwen** [comment]
Hi, I'm also very interested your job. Could you please release the ObjectNav evalution code. Thanks!

**Comment by srama2512** [comment]
@zenght  - Due to unforeseen circumstances on my end, this was delayed quite a bit. I've released the complete ObjectNav code + instructions in case you still need them.

@Routine113  @SJingwen  - Thank you for your interest. I've released the complete code. Please feel free to re-open this issue, or raise a new issue as they arise.
